name = "SQLiteCompress"
uuid = "ca66c970-58dd-40fd-84ba-8333ff914a26"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.0"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
DBInterface = "2.4.1"
SQLite = "1.1.4"
TranscodingStreams = "0.9.5"
julia = "1.6"
